#%RAML 1.0
  title: good
  description: 204 with body

  /resources:
    description: collection of resources
    get:
      
    /{resourceId}:
      description: single resource
      get:
        responses:
          204:
            body:
              application/json:
                {}
            
